--
-- PostgreSQL database dump
--

\restrict CxHlwynfqex0dO0nbsFdF1PrQkEN7ri8G7jg7kwCQHVwAwePfae7S6etbnBSZCg

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: announcements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    is_active boolean,
    priority character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    author_id bigint NOT NULL,
    course_id bigint,
    CONSTRAINT announcements_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[])))
);


ALTER TABLE public.announcements OWNER TO postgres;

--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignment_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignment_files (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size bigint,
    mime_type character varying(255),
    original_name character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone,
    assignment_id bigint NOT NULL
);


ALTER TABLE public.assignment_files OWNER TO postgres;

--
-- Name: assignment_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assignment_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignment_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    due_date timestamp(6) without time zone NOT NULL,
    max_points integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    course_id bigint
);


ALTER TABLE public.assignments OWNER TO postgres;

--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.course_enrollments (
    id bigint NOT NULL,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    enrolled_at timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(255) DEFAULT 'ENROLLED'::character varying NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT course_enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['ENROLLED'::character varying, 'COMPLETED'::character varying, 'DROPPED'::character varying])::text[])))
);


ALTER TABLE public.course_enrollments OWNER TO postgres;

--
-- Name: course_enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.course_enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.course_enrollments_id_seq OWNER TO postgres;

--
-- Name: course_enrollments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.course_enrollments_id_seq OWNED BY public.course_enrollments.id;


--
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    credits integer NOT NULL,
    description text,
    max_students integer,
    semester character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    teacher_id bigint,
    schedule character varying(255)
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forums; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forums (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.forums OWNER TO postgres;

--
-- Name: forums_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forums ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forums_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.materials (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    file_type character varying(255) NOT NULL,
    course_id bigint NOT NULL,
    download_count integer,
    uploaded_at timestamp(6) without time zone,
    title character varying(255) DEFAULT 'Document'::character varying NOT NULL
);


ALTER TABLE public.materials OWNER TO postgres;

--
-- Name: materials_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    is_archived boolean,
    is_read boolean,
    is_starred boolean,
    subject character varying(255) NOT NULL,
    course_id bigint,
    receiver_id bigint,
    sender_id bigint
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO postgres;

--
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.migrations_id_seq OWNER TO postgres;

--
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    action_url character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message text NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personal_access_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personal_access_tokens (
    id bigint NOT NULL,
    tokenable_type character varying(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    token character varying(64) NOT NULL,
    abilities text,
    last_used_at timestamp(0) without time zone,
    expires_at timestamp(0) without time zone,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);


ALTER TABLE public.personal_access_tokens OWNER TO postgres;

--
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.personal_access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.personal_access_tokens_id_seq OWNER TO postgres;

--
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.personal_access_tokens_id_seq OWNED BY public.personal_access_tokens.id;


--
-- Name: posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    likes_count integer,
    author_id bigint,
    topic_id bigint
);


ALTER TABLE public.posts OWNER TO postgres;

--
-- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submission_files (
    id bigint NOT NULL,
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size bigint,
    mime_type character varying(255),
    original_name character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone,
    submission_id bigint NOT NULL
);


ALTER TABLE public.submission_files OWNER TO postgres;

--
-- Name: submission_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.submission_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submissions (
    id bigint NOT NULL,
    content text,
    feedback text,
    grade integer,
    graded_at timestamp(6) without time zone,
    submitted_at timestamp(6) without time zone,
    assignment_id bigint NOT NULL,
    graded_by bigint,
    student_id bigint NOT NULL
);


ALTER TABLE public.submissions OWNER TO postgres;

--
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topics (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone,
    likes_count integer,
    priority character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    views integer,
    author_id bigint NOT NULL,
    forum_id bigint NOT NULL
);


ALTER TABLE public.topics OWNER TO postgres;

--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    address character varying(255),
    bio text,
    created_at timestamp(6) without time zone,
    department character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    permissions character varying(255),
    phone character varying(255),
    role character varying(255),
    semester character varying(255),
    specialty character varying(255),
    status character varying(255),
    student_id character varying(255),
    updated_at timestamp(6) without time zone,
    reset_token character varying(255),
    reset_token_expiry timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'PENDING'::character varying, 'SUSPENDED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_enrollments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollments ALTER COLUMN id SET DEFAULT nextval('public.course_enrollments_id_seq'::regclass);


--
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- Name: personal_access_tokens id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens ALTER COLUMN id SET DEFAULT nextval('public.personal_access_tokens_id_seq'::regclass);


--
-- Data for Name: announcements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.announcements (id, content, created_at, expires_at, is_active, priority, title, updated_at, author_id, course_id) FROM stdin;
2	Le cours en developpement mobile est reporte jusqu'au jeudi 10 fevrier..	2026-02-02 15:15:55.861319	2026-02-07 15:15:00	t	LOW	Cours Java reporté 	2026-02-02 15:18:07.605354	2	\N
3	A ne pas manquer !	2026-02-02 15:16:59.20766	2026-02-08 15:29:00	t	MEDIUM	Cours important	2026-02-02 15:29:15.990399	2	20
4	Une certification mise en place par 3fpt et disponibles pour tous les etudiants	2026-02-02 15:17:21.686102	2026-02-12 15:17:00	t	HIGH	Certification gratuite	2026-02-02 15:31:10.807479	2	20
\.


--
-- Data for Name: assignment_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assignment_files (id, file_name, file_path, file_size, mime_type, original_name, uploaded_at, assignment_id) FROM stdin;
\.


--
-- Data for Name: assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assignments (id, created_at, description, due_date, max_points, title, updated_at, course_id) FROM stdin;
1	2026-02-01 02:26:50.558723	Créer une application React complète	2026-02-08 02:26:50.55756	100	Projet React	2026-02-01 02:26:50.558753	1
2	2026-02-01 02:26:50.564631	Concevoir un modèle de base de données	2026-02-15 02:26:50.564127	80	Modélisation BDD	2026-02-01 02:26:50.564794	2
7	2026-02-01 03:05:42.069995	TN\n\nGestion des Devoirs\nCréez et gérez les devoirs de vos étudiants\n\nNouveau Devoir\nMes Devoirs\nSoumissions\nCorrection\nProjet React\nDéveloppement Web Avancé\nCréer une application React complète\n\nDate limite:\n\nDate limite:\n08/02/2026\n\nD\n	2026-02-26 03:11:00	100	test	2026-02-01 03:05:42.070012	\N
8	2026-02-01 03:09:47.900862	nouveanouveanouveanouveanouveanouveanouveanouveanouveanouveanouveanouveanouvea	2026-02-06 03:09:00	100	francais	2026-02-01 03:09:47.900882	\N
11	2026-02-01 14:58:24.65058	C'est un nouveau devoir en Java	2026-02-06 14:58:00	100	Devoir Java	2026-02-01 14:58:24.650594	5
5	2026-02-01 02:30:08.575319	C'est un devoir de projet a rendre	2026-02-06 02:55:00	204	Arts Visuels	2026-02-02 13:10:37.19407	19
9	2026-02-01 03:15:57.867941	C'est un devoir a faire sous forme de projet	2026-02-19 03:15:00	99	Ingenierie Logicielle	2026-02-02 13:11:45.344893	2
3	2026-02-01 02:28:13.302966	Concevoir un jeux video dynamique	2026-02-13 03:02:00	20	Conception d'application de jeux video	2026-02-02 13:12:26.975044	5
4	2026-02-01 02:28:41.762041	Devoir general	2026-02-06 02:28:00	20	Devoir d'Anglais	2026-02-02 13:13:01.591337	1
6	2026-02-01 02:33:47.111607	Un examen a faire e equipe de deux personnes	2026-01-21 02:33:00	20	Projet de fin d'etudes	2026-02-02 13:14:16.707613	20
10	2026-02-01 03:18:26.709363	Application de gestion desd marches publiques	2026-02-12 03:18:00	100	Application mobile	2026-02-02 13:14:49.942643	1
\.


--
-- Data for Name: course_enrollments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.course_enrollments (id, course_id, student_id, enrolled_at, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses (id, code, created_at, credits, description, max_students, semester, title, updated_at, teacher_id, schedule) FROM stdin;
6	TESTDELA-M2	2026-02-01 14:59:27.500909	3	Un nouveau test de nombre	8	S1	Test de la mention de nombre etudiant	2026-02-01 14:59:27.500942	\N	\N
20	ANG337	2026-02-02 12:32:25.07696	10	C'est un nouveau cours d'angular qui vous permettra de developper votre niveau en front end avec un framework js	30	S2	Angular	2026-02-02 12:58:18.35435	5	Jeudi 09:30-11:00
18	COI361	2026-02-01 17:58:23.54494	3	dddfffffffff	30	S1	Anglais debutant	2026-02-02 13:01:04.250865	5	Mercredi 14:00-16:00
19	COI132	2026-02-01 17:59:17.710034	3	Un cours pour les professionel	30	S1	Cours du soir en Arts Visuels	2026-02-02 13:07:21.231326	5	Mercredi 20:00-22:00
2	BDD-M2	2026-02-01 02:26:50.551996	4	Conception et gestion de bases de données	25	S1	Base de Données	2026-02-02 15:26:36.772873	2	Mardi 16:26-17:27
1	DWA-M2	2026-02-01 02:26:50.539314	6	Cours sur les technologies web modernes	32	S2	Développement Web Avancé	2026-02-02 21:01:55.272381	2	\N
10	COURSNOU-M2	2026-02-01 15:10:44.255312	3	je teste le nombre de support	30	S1	Nouveau cours	2026-02-02 21:29:05.8429	4	Mercredi 16:00-15:00
5	JAVASPRI-M2	2026-02-01 14:56:42.967509	6	Un cours centre sur la technologie Java qui va vous permettre d'avoir un niveau avancé à une technologie robuste	45	S1	Java Spring Boot	2026-02-02 23:49:28.806065	\N	\N
\.


--
-- Data for Name: forums; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forums (id, created_at, description, name, updated_at) FROM stdin;
1	2026-02-01 02:26:51.072086	Discussions sur les patterns, microservices et architecture système	Architecture Logicielle	2026-02-01 02:26:51.072113
2	2026-02-01 02:26:51.082426	Machine Learning, Deep Learning et IA générative	Intelligence Artificielle	2026-02-01 02:26:51.082454
3	2026-02-01 02:26:51.086408	Cybersécurité, cryptographie et protection des données	Sécurité Informatique	2026-02-01 02:26:51.086432
4	2026-02-01 02:26:51.098706	Analyse de données, visualisation et Big Data	Data Science	2026-02-01 02:26:51.098725
5	2026-02-01 02:26:51.106856	Partage d'expériences et conseils pour les projets	Projet de Fin d'Études	2026-02-01 02:26:51.106874
\.


--
-- Data for Name: materials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.materials (id, created_at, file_name, file_path, file_size, file_type, course_id, download_count, uploaded_at, title) FROM stdin;
1	2026-02-01 15:07:58.629358	rapport.pdf	uploads/materials/1769958478621_rapport.pdf	20711	application/pdf	5	\N	\N	Document
3	2026-02-01 15:10:44.287274	rapport.pdf	uploads/materials/1769958644285_rapport.pdf	20711	application/pdf	10	\N	\N	Document
5	\N	Bilan Financier - Cérémonie dr Remise Des Prix.docx	uploads/materials/19_Bilan Financier - Cérémonie dr Remise Des Prix.docx	16818	docx	19	0	2026-02-01 17:59:17.807477	Bilan Financier - Cérémonie dr Remise Des Prix.docx
6	\N	rapport.pdf	uploads/materials/20_rapport.pdf	20711	pdf	20	0	2026-02-02 12:32:25.292898	rapport.pdf
7	\N	rapport.pdf	uploads/materials/20_rapport.pdf	20711	pdf	20	0	2026-02-02 12:55:45.202997	rapport.pdf
8	\N	rapport.pdf	uploads/materials/20_rapport.pdf	20711	pdf	20	0	2026-02-02 12:56:19.494152	rapport.pdf
9	\N	rapport.pdf	uploads/materials/20_rapport.pdf	20711	pdf	20	0	2026-02-02 12:56:19.496514	rapport.pdf
10	\N	rapport.pdf	uploads/materials/18_rapport.pdf	20711	pdf	18	0	2026-02-02 13:01:04.473293	rapport.pdf
11	\N	rapport.pdf	uploads/materials/19_rapport.pdf	20711	pdf	19	0	2026-02-02 13:01:39.603517	rapport.pdf
12	\N	rapport.pdf	uploads/materials/10_rapport.pdf	20711	pdf	10	0	2026-02-02 13:04:23.087849	rapport.pdf
13	\N	rapport.pdf	uploads/materials/19_rapport.pdf	20711	pdf	19	0	2026-02-02 13:07:21.320985	rapport.pdf
14	\N	rapport.pdf	uploads/materials/2_rapport.pdf	20711	pdf	2	0	2026-02-02 15:26:37.08618	rapport.pdf
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, content, created_at, is_archived, is_read, is_starred, subject, course_id, receiver_id, sender_id) FROM stdin;
1	Bonjour Jean	2026-02-01 15:15:52.44133	f	t	f	Salutations	2	2	5
10	un nouveau message 	2026-02-02 10:12:27.937318	f	t	f	Je test 	2	5	1
7	Tu es brave	2026-02-01 15:48:06.371592	f	t	f	Bravo	2	3	3
4	merci	2026-02-01 15:29:38.214971	f	t	f	Re: je test	\N	5	5
11	gentil.	2026-02-02 10:17:03.238681	f	t	f	Re: Bravo	\N	3	1
9	oui	2026-02-01 18:15:30.316215	f	t	f	Re: Felicitations	\N	3	1
14	word	2026-02-02 11:05:20.416526	f	t	f	Hello	\N	1	3
12	nnnn	2026-02-02 10:49:20.426248	f	t	f	Re: Je test 	\N	1	3
17	salut	2026-02-02 11:10:41.733532	f	t	f	Message	\N	4	3
13	merci	2026-02-02 11:03:00.184659	f	t	f	Message	\N	1	3
15	Bonjour	2026-02-02 11:05:36.572316	f	t	f	oui	\N	3	3
18	Hello !\n	2026-02-02 11:11:15.263796	f	t	f	Salutations	\N	3	3
21	ffff	2026-02-02 11:20:24.697789	f	t	f	ff	\N	1	3
19	ffffff	2026-02-02 11:14:52.769809	f	t	f	je test	\N	1	3
16	Bonjour Tafsir	2026-02-02 11:06:05.185167	f	t	f	Good morning	\N	4	3
20	nnn	2026-02-02 11:20:07.514176	f	t	f	je test	\N	3	3
22	ddd	2026-02-02 11:20:35.834425	f	t	f	je test	\N	3	3
23	ddd	2026-02-02 11:20:35.878493	f	t	f	je test	\N	3	3
26	Merci pour tout !	2026-02-02 13:25:16.623638	f	t	f	Remerciements	\N	1	3
24	je suis a la recherche du forum de discussion	2026-02-02 11:24:24.458523	f	t	f	recherche	\N	1	3
25	On fait cours ce soir ?	2026-02-02 11:24:45.025978	f	t	f	Cours	\N	4	3
27	Pourquoi les etudiants sont sous absents aujourd'hui ?	2026-02-02 13:35:09.352202	f	t	f	Question	\N	1	2
28	Bonjour, Ah, on a oublie de vous informer de la sortie pedagogique d'aujourd'hui. Merci de nous excuser.	2026-02-02 13:36:27.968964	f	t	f	Message	\N	2	1
29	Merci pour votre message.	2026-02-02 13:37:03.478414	f	t	f	Message	\N	1	2
6	Toutes mes felicitations pour ta reussite	2026-02-01 15:47:47.832869	f	t	f	Felicitations	\N	1	3
8	rrr	2026-02-01 18:15:20.815835	f	t	f	je test	\N	2	1
5	njj	2026-02-01 15:31:42.708314	f	t	f	je test	\N	2	5
3	jjjjj	2026-02-01 15:23:01.226709	f	t	f	je test	\N	3	5
2	salut	2026-02-01 15:16:09.539148	f	t	f	salutations 2	\N	5	5
\.


--
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.migrations (id, migration, batch) FROM stdin;
1	2019_12_14_000001_create_personal_access_tokens_table	1
2	2024_01_01_000001_create_users_table	1
3	2024_01_01_000002_create_courses_table	1
4	2024_01_01_000003_create_course_enrollments_table	1
5	2024_01_01_000004_create_assignments_table	1
6	2024_01_01_000005_create_submissions_table	1
7	2024_01_01_000006_create_messages_table	1
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, action_url, created_at, is_read, message, title, type, user_id) FROM stdin;
1	/messages	2026-02-01 15:15:52.459662	f	Nouveau message de Tafsir Haby NIANG: Salutations	Nouveau message	message	2
2	/messages	2026-02-01 15:16:09.558412	f	Nouveau message de Tafsir Haby NIANG: salutations 2	Nouveau message	message	5
3	/messages	2026-02-01 15:23:01.32038	f	Nouveau message de Tafsir Haby NIANG: je test	Nouveau message	message	3
4	/messages	2026-02-01 15:29:38.397861	f	Nouveau message de Tafsir Haby NIANG: Re: je test	Nouveau message	message	5
5	/messages	2026-02-01 15:31:42.728796	f	Nouveau message de Tafsir Haby NIANG: je test	Nouveau message	message	2
6	/messages	2026-02-01 15:47:47.949226	f	Nouveau message de Marie Martin: Felicitations	Nouveau message	message	1
7	/messages	2026-02-01 15:48:06.394929	f	Nouveau message de Marie Martin: Bravo	Nouveau message	message	3
8	/messages	2026-02-01 18:15:21.272978	f	Nouveau message de Admin Campus: je test	Nouveau message	message	2
9	/messages	2026-02-01 18:15:30.39977	f	Nouveau message de Admin Campus: Re: Felicitations	Nouveau message	message	3
10	/messages	2026-02-02 10:12:28.064131	f	Nouveau message de Admin Campus: Je test 	Nouveau message	message	5
11	/messages	2026-02-02 10:17:03.942105	f	Nouveau message de Admin Campus: Re: Bravo	Nouveau message	message	3
12	/messages	2026-02-02 10:49:20.917698	f	Nouveau message de Marie Martin: Re: Je test 	Nouveau message	message	1
13	/messages	2026-02-02 11:03:00.514382	f	Nouveau message de Marie Martin: Message	Nouveau message	message	1
14	/messages	2026-02-02 11:05:20.514562	f	Nouveau message de Marie Martin: Hello	Nouveau message	message	1
15	/messages	2026-02-02 11:05:36.624377	f	Nouveau message de Marie Martin: oui	Nouveau message	message	3
16	/messages	2026-02-02 11:06:05.295566	f	Nouveau message de Marie Martin: Good morning	Nouveau message	message	4
17	/messages	2026-02-02 11:10:41.805456	f	Nouveau message de Marie Martin: Message	Nouveau message	message	4
18	/messages	2026-02-02 11:11:15.346427	f	Nouveau message de Marie Martin: Salutations	Nouveau message	message	3
19	/messages	2026-02-02 11:14:52.784416	f	Nouveau message de Marie Martin: je test	Nouveau message	message	1
20	/messages	2026-02-02 11:20:07.571679	f	Nouveau message de Marie Martin: je test	Nouveau message	message	3
21	/messages	2026-02-02 11:20:24.716708	f	Nouveau message de Marie Martin: ff	Nouveau message	message	1
22	/messages	2026-02-02 11:20:35.937783	f	Nouveau message de Marie Martin: je test	Nouveau message	message	3
23	/messages	2026-02-02 11:20:35.951606	f	Nouveau message de Marie Martin: je test	Nouveau message	message	3
24	/messages	2026-02-02 11:24:24.498112	f	Nouveau message de Marie Martin: recherche	Nouveau message	message	1
25	/messages	2026-02-02 11:24:45.096229	f	Nouveau message de Marie Martin: Cours	Nouveau message	message	4
26	/messages	2026-02-02 13:25:16.713053	f	Nouveau message de Marie Martin: Remerciements	Nouveau message	message	1
27	/messages	2026-02-02 13:35:09.367143	f	Nouveau message de Jean Dupont: Question	Nouveau message	message	1
28	/messages	2026-02-02 13:36:27.979722	f	Nouveau message de Admin Campus: Message	Nouveau message	message	2
29	/messages	2026-02-02 13:37:03.488037	f	Nouveau message de Jean Dupont: Message	Nouveau message	message	1
\.


--
-- Data for Name: personal_access_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.personal_access_tokens (id, tokenable_type, tokenable_id, name, token, abilities, last_used_at, expires_at, created_at, updated_at) FROM stdin;
1	App\\Models\\User	1	auth_token	41dbe965404dfd88dbdfac850280c2e79d806d151b8d4797ff36f554843f9f15	["*"]	\N	\N	2026-01-20 21:50:41	2026-01-20 21:50:41
2	App\\Models\\User	1	auth_token	870572f795cfc4b8f7bf73b600cfa3eff9dc461daf58550987f7ef6f44cb10e1	["*"]	\N	\N	2026-01-20 21:51:17	2026-01-20 21:51:17
3	App\\Models\\User	2	auth_token	f42421ccac63757feb3a216f3063f431a6be47c805d39cc2025795eedd6a480f	["*"]	\N	\N	2026-01-20 21:52:58	2026-01-20 21:52:58
4	App\\Models\\User	2	auth_token	1163c8a58fd7bb967afd64f868d0cd373fac09bb29b9fda8b7d7773386998ca7	["*"]	2026-01-20 21:54:28	\N	2026-01-20 21:54:19	2026-01-20 21:54:28
5	App\\Models\\User	2	auth_token	0055286ade57f603afee65b1f770117bd288a3df9e4e46bd921b0c281c49aa8e	["*"]	\N	\N	2026-01-20 22:13:24	2026-01-20 22:13:24
\.


--
-- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts (id, content, created_at, likes_count, author_id, topic_id) FROM stdin;
1	Excellente question ! Le pattern Observer est parfait pour ton cas. Voici un exemple simple...	2026-02-01 02:26:51.139437	5	2	1
2	Je rajouterais qu'avec React, tu peux aussi utiliser des hooks personnalisés pour implémenter ce pattern.	2026-02-01 02:26:51.14562	2	1	1
3	merci	2026-02-01 15:42:00.887073	0	1	3
4	Bienvenue	2026-02-01 15:47:03.191588	0	1	4
5	Bien recu.	2026-02-02 13:33:05.32979	2	1	6
\.


--
-- Data for Name: submission_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.submission_files (id, file_name, file_path, file_size, mime_type, original_name, uploaded_at, submission_id) FROM stdin;
1	7a83e3b7-c8c1-477c-b496-acf3254fc70d_Bilan Financier - Cérémonie dr Remise Des Prix.pdf	uploads/submissions/7a83e3b7-c8c1-477c-b496-acf3254fc70d_Bilan Financier - Cérémonie dr Remise Des Prix.pdf	458326	application/pdf	Bilan Financier - Cérémonie dr Remise Des Prix.pdf	2026-02-01 18:30:19.703064	1
2	1c488b20-1fdd-4e38-a346-5d045e641672_Bilan Financier - Cérémonie dr Remise Des Prix.docx	uploads/submissions/1c488b20-1fdd-4e38-a346-5d045e641672_Bilan Financier - Cérémonie dr Remise Des Prix.docx	16818	application/vnd.openxmlformats-officedocument.wordprocessingml.document	Bilan Financier - Cérémonie dr Remise Des Prix.docx	2026-02-01 18:38:05.002789	2
3	bfcea867-f817-4fc8-b481-53c16cd99c5c_Fiche des Notes - CP2I - Deuxième Edition.docx	uploads/submissions/bfcea867-f817-4fc8-b481-53c16cd99c5c_Fiche des Notes - CP2I - Deuxième Edition.docx	37953	application/vnd.openxmlformats-officedocument.wordprocessingml.document	Fiche des Notes - CP2I - Deuxième Edition.docx	2026-02-01 18:40:16.830075	1
4	3e81e131-94f8-4eb6-8e0f-cfebfc0178c2_rapport.pdf	uploads/submissions/3e81e131-94f8-4eb6-8e0f-cfebfc0178c2_rapport.pdf	20711	application/pdf	rapport.pdf	2026-02-02 23:59:48.104258	3
\.


--
-- Data for Name: submissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.submissions (id, content, feedback, grade, graded_at, submitted_at, assignment_id, graded_by, student_id) FROM stdin;
1	\N		6	2026-02-01 19:07:15.768121	2026-02-01 18:40:16.815125	1	\N	3
2	\N		11	2026-02-01 19:07:37.793364	2026-02-01 18:38:04.781931	2	\N	3
3	Merci d'augmenter la date limite de depot.	C'est un bon travail, bonne continuation.	100	2026-02-03 00:02:37.628663	2026-02-02 23:59:48.004697	8	\N	3
\.


--
-- Data for Name: topics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.topics (id, content, created_at, likes_count, priority, title, updated_at, views, author_id, forum_id) FROM stdin;
2	nn	2026-02-01 15:34:54.367842	0	normal	test	2026-02-01 15:34:54.367848	0	1	3
3	je suis en test	2026-02-01 15:35:31.793159	0	high	oui	2026-02-01 15:41:46.076959	1	1	4
4	merci	2026-02-01 15:46:13.665759	0	high	Je suis etudiant qui test	2026-02-01 15:46:56.051541	1	1	2
5	ccccccccccccc	2026-02-01 18:03:19.994073	0	normal	cc	2026-02-01 18:03:19.994473	0	1	4
6	Voici votre sujet de memoire a traiter en deux.	2026-02-02 13:32:27.280862	1	low	Sujet de memoire	2026-02-02 13:33:02.427189	1	1	5
1	Bonjour à tous,\n\nJe travaille sur un projet où je dois implémenter le pattern Observer en JavaScript/TypeScript.	2026-02-01 02:26:51.122649	0	NORMAL	Aide pour implémenter un pattern Observer	2026-02-02 23:39:53.761816	1	3	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, address, bio, created_at, department, email, first_name, last_name, password, permissions, phone, role, semester, specialty, status, student_id, updated_at, reset_token, reset_token_expiry) FROM stdin;
3	\N	\N	2026-02-01 02:26:50.530687	\N	etudiant@campus.sn	Marie	Martin	$2a$10$Q.hYnK8avZGRKbBEtyD7O.ypRutOnx1RqwfXjPR.281LkPhhFr4oW	\N	\N	STUDENT	\N	\N	ACTIVE	\N	2026-02-01 02:26:50.530714	\N	\N
4	\N	\N	2026-02-01 02:39:39.803627	DATA	tafsir@campus.sn	Tafsir-Ens	Prof	$2a$10$RH4Sou0/e9ae.u0zxLuwE.8QoPb.3shFl5PfAbj04YjmGIBmwyEIy	\N	+221776290639	TEACHER	\N	\N	ACTIVE	\N	2026-02-02 15:56:01.630888	\N	\N
5	Mauritanie	je suis etudiant	2026-02-01 02:47:21.482339	\N	tafsirhabyng27@gmail.com	Tafsir Haby	NIANG	$2a$10$EMC1f/8/FHziV3LMK11KL.Qo.xbN/nDwQrBbcpX4LvgbouiIKS2d.	\N	+221776290639	TEACHER	\N	\N	ACTIVE	\N	2026-02-02 22:45:50.916631	\N	\N
2	\N	\N	2026-02-01 02:26:50.036355	\N	prof@campus.sn	Prof	Teacher	$2a$10$v7EMdHgfJv967exeb9Wm8.WffjQbPt1.wkW2FXmbPnTxNJ74tA6QG	\N	+221775556677	TEACHER	\N	\N	ACTIVE	\N	2026-02-02 23:58:03.069728	\N	\N
1	\N	\N	2026-02-01 02:26:49.667209	\N	admin@campus.sn	Admin	User	$2a$10$qUiphLWUKq3NwFw.sgSh6eB2CvYI4hYs.1.2K.Ne3GHOT5kse1EK.	\N	776665544	ADMIN	\N	\N	ACTIVE	\N	2026-02-03 18:41:41.045545	\N	\N
\.


--
-- Name: announcements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.announcements_id_seq', 4, true);


--
-- Name: assignment_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assignment_files_id_seq', 1, false);


--
-- Name: assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assignments_id_seq', 11, true);


--
-- Name: course_enrollments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.course_enrollments_id_seq', 1, false);


--
-- Name: courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_id_seq', 20, true);


--
-- Name: forums_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forums_id_seq', 5, true);


--
-- Name: materials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.materials_id_seq', 14, true);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 29, true);


--
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.migrations_id_seq', 7, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 29, true);


--
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.personal_access_tokens_id_seq', 5, true);


--
-- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_id_seq', 5, true);


--
-- Name: submission_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.submission_files_id_seq', 4, true);


--
-- Name: submissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.submissions_id_seq', 3, true);


--
-- Name: topics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.topics_id_seq', 6, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: assignment_files assignment_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_files
    ADD CONSTRAINT assignment_files_pkey PRIMARY KEY (id);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: course_enrollments course_enrollments_course_id_student_id_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollments
    ADD CONSTRAINT course_enrollments_course_id_student_id_unique UNIQUE (course_id, student_id);


--
-- Name: course_enrollments course_enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.course_enrollments
    ADD CONSTRAINT course_enrollments_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: forums forums_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forums
    ADD CONSTRAINT forums_pkey PRIMARY KEY (id);


--
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: personal_access_tokens personal_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);


--
-- Name: personal_access_tokens personal_access_tokens_token_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_token_unique UNIQUE (token);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: submission_files submission_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submission_files
    ADD CONSTRAINT submission_files_pkey PRIMARY KEY (id);


--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: course_enrollments_course_id_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX course_enrollments_course_id_index ON public.course_enrollments USING btree (course_id);


--
-- Name: course_enrollments_student_id_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX course_enrollments_student_id_index ON public.course_enrollments USING btree (student_id);


--
-- Name: personal_access_tokens_tokenable_type_tokenable_id_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX personal_access_tokens_tokenable_type_tokenable_id_index ON public.personal_access_tokens USING btree (tokenable_type, tokenable_id);


--
-- Name: announcements fk1pgl63iwbqvmngumhvr3xopg3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fk1pgl63iwbqvmngumhvr3xopg3 FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: submissions fk3p6y8mnhpwusdgqrdl4hcl72m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk3p6y8mnhpwusdgqrdl4hcl72m FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: messages fk64amm5xxcsy969lnd3r80qgkn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk64amm5xxcsy969lnd3r80qgkn FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: assignments fk6p1m72jobsvmrrn4bpj4168mg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fk6p1m72jobsvmrrn4bpj4168mg FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: posts fk6xvn0811tkyo3nfjk2xvqx6ns; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk6xvn0811tkyo3nfjk2xvqx6ns FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: topics fk7xkxef4fwbjec06isf4ims4gr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fk7xkxef4fwbjec06isf4ims4gr FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: assignment_files fk8x2j84q2wywvo48llsy0lk34l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assignment_files
    ADD CONSTRAINT fk8x2j84q2wywvo48llsy0lk34l FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: announcements fkcbrf5570bepj9wk21ofsrpwp2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT fkcbrf5570bepj9wk21ofsrpwp2 FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: materials fkdky0bj42nucpuas522aj6yoc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT fkdky0bj42nucpuas522aj6yoc FOREIGN KEY (course_id) REFERENCES public.courses(id);


--
-- Name: topics fkh9cpbcvpen6awkeyuxcx9026e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT fkh9cpbcvpen6awkeyuxcx9026e FOREIGN KEY (forum_id) REFERENCES public.forums(id);


--
-- Name: submissions fkmjfva3nkq8vlatkp2mk3678hh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkmjfva3nkq8vlatkp2mk3678hh FOREIGN KEY (graded_by) REFERENCES public.users(id);


--
-- Name: submission_files fkrc3p2q2a21qn0be2l4py1uc5c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submission_files
    ADD CONSTRAINT fkrc3p2q2a21qn0be2l4py1uc5c FOREIGN KEY (submission_id) REFERENCES public.submissions(id);


--
-- Name: posts fkrfchr8dax0kfngvvkbteh5n7h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkrfchr8dax0kfngvvkbteh5n7h FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Name: submissions fkrirbb44savy2g7nws0hoxs949; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkrirbb44savy2g7nws0hoxs949 FOREIGN KEY (assignment_id) REFERENCES public.assignments(id);


--
-- Name: messages fkt05r0b6n0iis8u7dfna4xdh73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: courses fkt4ba5fab1x56tmt4nsypv5lm5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fkt4ba5fab1x56tmt4nsypv5lm5 FOREIGN KEY (teacher_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict CxHlwynfqex0dO0nbsFdF1PrQkEN7ri8G7jg7kwCQHVwAwePfae7S6etbnBSZCg

