-- Script pour ajouter la colonne schedule dans H2
INSERT INTO INFORMATION_SCHEMA.COLUMNS (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE) 
SELECT 'PUBLIC', 'PUBLIC', 'COURSES', 'SCHEDULE', 'VARCHAR(255)', 'YES' 
WHERE NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'COURSES' AND COLUMN_NAME = 'SCHEDULE'
);

-- Alternative: Utiliser ALTER TABLE directement
-- ALTER TABLE COURSES ADD COLUMN IF NOT EXISTS SCHEDULE VARCHAR(255);