#!/bin/bash

echo "🚀 Backend CampusMaster créé avec succès !"
echo ""
echo "📁 Structure complète :"
echo "  ✅ Entités JPA (User, Course, Assignment, Submission)"
echo "  ✅ Repositories Spring Data"
echo "  ✅ Services métier"
echo "  ✅ Contrôleurs REST"
echo "  ✅ DTOs d'authentification"
echo "  ✅ Configuration sécurité"
echo "  ✅ Données de test"
echo ""
echo "🔧 Configuration :"
echo "  - Base de données : H2 (en mémoire)"
echo "  - Port : 8080"
echo "  - Console H2 : http://localhost:8080/h2-console"
echo ""
echo "📋 Comptes de test :"
echo "  - Admin: admin@campus.fr / password"
echo "  - Enseignant: prof@campus.fr / password"
echo "  - Étudiant: etudiant@campus.fr / password"
echo ""
echo "🌐 Endpoints API :"
echo "  - POST /api/auth/login"
echo "  - POST /api/auth/register"
echo "  - GET /api/courses"
echo "  - GET /api/assignments"
echo "  - GET /api/submissions"
echo ""
echo "▶️  Pour démarrer le serveur :"
echo "   cd campusmaster-backend"
echo "   ./mvnw spring-boot:run"
echo ""
echo "🧪 Test rapide :"
echo "   curl http://localhost:8080/api/courses"